export enum EPaymentMethod {
  CASH = "CASH",
  MOMO = "MOMO",
  BANK_TRANSFER = "BANK_TRANSFER",
}

export enum EOrderStatus {
  PENDING = "PENDING",
  CONFIRMED = "CONFIRMED",
  PAID = "PAID",
  PAYMENT_FAILED = "PAYMENT_FAILED",
  PROCESSING = "PROCESSING",
  SHIPPED = "SHIPPED",
  DELIVERED = "DELIVERED",
  CANCELLED = "CANCELLED",
}
